const mongoose = require("mongoose");

/**
 * Interview Report Schema   
 * 
 * - job description schema: String
 * - resume text: String
 * - self description: String
 * 
 *  
 *  This schema defines the structure of an interview report generated by the AI service. It includes the following fields: 
 * - matchScore : Number
 * 
 * - Technical questions : [{
 *                             question: "",
 *                             intention: "",
 *                             answer: "",
 *                      }]
 * - Behavioral questions: [{
 *                             question: "",
 *                             intention: "",
 *                             answer: "",
 *                      }]
 * - Skill gaps: [{
 *                  skill: "",
 *                  severity: {
 *                          type: String,
 *                          enum: {"low", "medium", "high"}
 *                   },
 *               }]
 * - Preparation plan: [{
 *                          day: Number,
 *                          focus: String,
 *                          tasks: {String},
 *                 }]
 */

const technicalQuestionSchema = new mongoose.Schema({
    question:{
        type: String,
        required: [true, "Technical question is required"]
    },
    intention:{
        type: String,
        required: [true, "Intention is required"]
    },
    answer:{
        type: String,
        required: [true, "Intention is required"]
    }
},{
    _id: false
});

const behavioralQuestionSchema = new mongoose.Schema({
    question:{
        type: String,
        required: [true, "Behavioral questions is required"]
    },
    intention:{
        type: String,
        required: [true, "Intention is required"]
    },
    answer:{
        type: String,
        required: [true, "Answer is required"]
    }
},{
    _id: false
});

const skillGapSchema = new mongoose.Schema({
    skill:{
        type: String,
        required: [true, "Skill is required"]
    },
    severity:{
        type: String,
        enum: ["low", "medium", "high"],
        required: [true, "Severity is required"]
    }
},{
    _id: false
});

const preparationPlanSchema = new mongoose.Schema({
    day:{
        type: Number,
        required: [true, "Day is required"]
    },
    focus:{
        type: String,
        required: [true, "Focus is required"]
    },
    tasks:{
        type: String,
        required: [true, "Taks is required"]
    }
},{
    _id: false
});

const interviewReportSchema = new mongoose.Schema({
    jobDescription: {
        type: String,
        required: [true, "Job description is required"]
    },
    resume: {
        type: String,
    },
    selfDescription: {
        type: String,
        required: [true, "Self description is required"]
    },
    matchScore: {
        type: Number,
        min: 0,
        max: 100
    },
    technicalQuestions: [technicalQuestionSchema],
    behavioralQuestions: [behavioralQuestionSchema],
    skillGaps: [skillGapSchema],
    preparationPlan: [preparationPlanSchema]
},{
    timestamps: true
});

const interviewReportModel = new mongoose.model("InterviewReport", interviewReportSchema);

module.exports = interviewReportModel;