const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
});

/**
 * Schema for the interview report generated by the AI using Zod.
 * The Schema defines the structure of the report, including match score, technical questions, behavioral questions, skill gaps, and preparation plan.
 */
const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate matches the job description."),
 
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical questions can be asked in interview"),
        intention: z.string().describe("The intention of interviewer behind asking the question"),
        answer: z.string().describe("How to answer this question in interview")
    })).describe("Technical questions that can be asked in interview along with their intention and suggested answers"),
 
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral questions can be asked in interview"),
        intention: z.string().describe("The intention of interviewer behind asking the question"),
        answer: z.string().describe("How to answer this question in interview")
    })).describe("Behavioral questions that can be asked in interview along with their intention and suggested answers"),
  
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lacking or needs improvement on"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity level of the skill gap")
    })).describe("List of skills in candidate's profile that are lacking or need improvement, along with their severity level"),
   
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day in the preparation plan, starting from 1"),
        focus: z.string().describe("The focus area for that day"),
        tasks: z.array(z.string().describe("The tasks to be completed on that day"))
    })).describe("A day-wise preparation plan for the candidate to improve their skills and prepare for the interview."),

    title: z.string().describe("The title of the job for which the interview report is generated"),
})

/**
 * Generates an interview report for a candidate based on their resume, self-description, and job description.
 */
async function generateInterviewReport({resume, selfDescription, jobDescription}){
    
    const prompt = `
    Generate an interview report for a candidate with the following details:
    RESUME:${resume}
    SELF DESCRIPTION:${selfDescription}
    JOB DESCRIPTION:${jobDescription}
    `;

    try{
    const interaction = await ai.interactions.create({
        model: "gemini-3.6-flash",
        input: prompt,
        response_format:{
            type: "text",
            mime_type:"application/json",
            schema: z.toJSONSchema(interviewReportSchema)
        }
    });

    // const report = JSON.parse(interaction.output_text);
    const report = interviewReportSchema.parse(JSON.parse(interaction.output_text));

    return report;

    }catch(err){
        console.log("Gemini Error:", err);
    }
}

/**
 * Generate a PDF from HTML using Puppeteer
 */
async function generatePdfFromHtml( html) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent( html, { waitUntil: 'networkidle0' });   // html is the HTML content to be converted to PDF and wait until the network is idle
    const pdfBuffer = await page.pdf({ format: 'A4', margin: {top: "20mm", bottom: "20mm", left: "15mm", right: "15mm"} });            // Generate PDF buffer from the page content
    await browser.close();

    return pdfBuffer;
}

/**
 * Generate html for pdf from ai
 */
async function generateResumePdf({resume, selfDescription, jobDescription}) {

    const resumePdfSchema = z.object({
        html: z.string().describe("A base64 encoded PDF file containing the candidate's resume, self-description, and job description formatted for printing.")
    });

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    try{
        const interaction = await ai.interactions.create({
            model: "gemini-3.6-flash",
            input:prompt,
            response_format: {
                type: "text",
                mime_type:"application/json",
                schema: z.toJSONSchema(resumePdfSchema)
            }
        })

        const resumePDF = resumePdfSchema.parse(JSON.parse(interaction.output_text));  // resumePDF is the HTML content returned by the AI service.

        const pdfBuffer = await generatePdfFromHtml(resumePDF.html);                   // Generate PDF buffer from the HTML content returned by the AI

        return pdfBuffer;

    } catch(err){
        console.log("Gemini Error:", err);
    }
}

module.exports = { generateInterviewReport, generateResumePdf};