const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
});

/**
 * Schema for the interview report generated by the AI using Zod.
 * The Schema defines the structure of the report, including match score, technical questions, behavioral questions, skill gaps, and preparation plan.
 */
const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate matches the job description."),
 
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical questions can be asked in interview"),
        intention: z.string().describe("The intention of interviewer behind asking the question"),
        answer: z.string().describe("How to answer this question in interview")
    })).describe("Technical questions that can be asked in interview along with their intention and suggested answers"),
 
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral questions can be asked in interview"),
        intention: z.string().describe("The intention of interviewer behind asking the question"),
        answer: z.string().describe("How to answer this question in interview")
    })).describe("Behavioral questions that can be asked in interview along with their intention and suggested answers"),
  
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lacking or needs improvement on"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity level of the skill gap")
    })).describe("List of skills in candidate's profile that are lacking or need improvement, along with their severity level"),
   
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day in the preparation plan, starting from 1"),
        focus: z.string().describe("The focus area for that day"),
        tasks: z.array(z.string().describe("The tasks to be completed on that day"))
    })).describe("A day-wise preparation plan for the candidate to improve their skills and prepare for the interview.")
})

/**
 * Generates an interview report for a candidate based on their resume, self-description, and job description.
 */
async function generateInterviewReport({resume, selfDescription, jobDescription}){
    
    const prompt = `
    Generate an interview report for a candidate with the following details:
    RESUME:${resume}
    SELF DESCRIPTION:${selfDescription}
    JOB DESCRIPTION:${jobDescription}
    `;

    console.log("Gemini response--------")
    try{
    const interaction = await ai.interactions.create({
        model: "gemini-3.6-flash",
        input: prompt,
        response_format:{
            type: "text",
            mime_type:"application/json",
            schema: z.toJSONSchema(interviewReportSchema)
        }
    });

    // const report = JSON.parse(interaction.output_text);
    const report = interviewReportSchema.parse(JSON.parse(interaction.output_text));

    return report;

    }catch(err){
        console.log("Gemini Error:", err);
    }
}

module.exports = generateInterviewReport;